name: Test coverage
on: [push]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
        with:
          coverageCommand: ls & pwd # make test-cov
          debug: true

