name: Test coverage
on: [push]
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

#      - name: Code Climate Coverage Action
#        uses: paambaati/codeclimate-action@v9.0.0
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.REPORTER_ID }}
#        with:
#          coverageCommand: make test-cov  # make test-cov
#          debug: true

